
server:
  port: 9291

spring:
  profiles:
    active: dev # dev test prod
  application:
    name: @project.name@
    version: @project.version@
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:1001

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.aidansu.mall.auth.feign.interceptor.TokenRelayRequestInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50